services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    networks:
      - qdrant_network
  app:
    build: .
    depends_on:
      - qdrant
    networks:
      - qdrant_network
    ports:
      - "8501:8501"
    env_file:
      - .env
networks:
  qdrant_network:
    name: qdrant_bridge
    driver: bridge